openapi: 3.0.3

info:
  title: Skeleton
  version: 1.0.0

paths: {}

components:
  parameters:
    apiVersion:
      name: apiVersion
      description: The API version.
      in: path
      required: true
      schema:
        type: integer
        minimum: 1
        maximum: 2
        default: 1

  responses:
    ClientError:
      description: An error occurred.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    Error:
      description: An error occurred.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    InvalidRequest:
      description: Validation error.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/InvalidRequest"

  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          description: Associated error code.
        error:
          type: string
          description: A message describing the error.
        messages:
          type: array
          items:
            type: string
            description: A detailed description of the error.
        extra:
          type: object
          description: Additional information about the error.
        trace:
          type: array
          items:
            type: object
            description: A stack trace of the error.
      required:
        - error
    InvalidRequest:
      type: object
      properties:
        message:
          type: string
          description: Human readable description of the error
        validation:
          type: object
          description: A detailed description of the error.
      required:
        - message
        - validation

  securitySchemes:
    Bearer:
      type: apiKey
      description: 'JWT authorization HTTP header using the Bearer scheme. Example: "Bearer {token}"'
      name: Authorization
      in: header

servers:
    - url: /
