CREATE GROUP ${GROUP};

CREATE USER ${MAIN_ROLE} WITH
	CREATEROLE
	IN GROUP ${GROUP}
	PASSWORD '${MAIN_ROLE_PASS}'
;

-- musl (Alpine) has no cs_CZ locale; use ICU collation for cs sorting instead.
CREATE DATABASE ${DB_NAME} WITH
	OWNER = ${MAIN_ROLE}
	ENCODING = UTF8
	LOCALE = 'C.UTF-8'
	LOCALE_PROVIDER = icu
	ICU_LOCALE = 'cs-CZ'
	TEMPLATE = template0
;

GRANT ALL PRIVILEGES
	ON DATABASE ${DB_NAME}
	TO ${POSTGRES_USER}
;

GRANT CONNECT
	ON DATABASE ${DB_NAME}
	TO GROUP ${GROUP}
;

CREATE USER ${READONLY_ROLE} WITH
	CREATEROLE
	IN GROUP ${GROUP}
	PASSWORD '${READONLY_ROLE_PASSWORD}'
;

GRANT SELECT
	ON ALL TABLES IN SCHEMA public
	TO ${READONLY_ROLE}
;
